### ISSUE TITLE
Make Room Reservations 

### ISSUE THREAD

**Issue by hjmjohnson** [brainhack-uiowa/uiowaBIDS#1]
CPH building.  Greg Charmichael stated he is happy to support our request for space.

Hans

**Comment by jdkent** [comment]
Thanks! :+1:  Would you know the cost of the space for a three day period (May 3,4,5)? Do we reserve individual rooms?

**Comment by hjmjohnson** [comment]
I think the cost will be $0.00 ☺

 

Hans

**Comment by jdkent** [comment]
Awesome! Do you know if we will have access to recording equipment in order to tape/stream the tutorial sessions?

**Comment by hjmjohnson** [comment]
I’m not sure about extra AV equipement, but we can use whatever is in those rooms.

 

Hans
