### ISSUE TITLE
Make 11x17 posters (20 or so ) to hang around

### ISSUE THREAD

**Issue by hjmjohnson** [brainhack-uiowa/uiowaBIDS#2]
You can print on my color tabloid printer in 4321 SC.

This poster PDF can be sent to IIBI as well.

**Comment by jdkent** [comment]
I've printed poster and posted a few around the medical campus MERF, BSB, etc. I'm planning on placing a few in the Seamans Center and other places

**Comment by hjmjohnson** [comment]
Can you send the PDF to the IIBI group and me?

**Comment by jdkent** [comment]
[brainhackposter.pdf](https://github.com/brainhack-uiowa/uiowaBIDS/files/1924889/brainhackposter.pdf)

Here is the poster, I don't believe I'm a part of the IIBI group.
